// Purpose: Verifies token signatures against immutable payload using server RSA public key.
import 'dart:convert';

import 'package:basic_utils/basic_utils.dart';
import 'package:flutter/foundation.dart';

import '../models/recharge_response.dart';

class TokenVerificationResult {
  final String tokenId;
  final bool isValid;
  final String? reason;

  const TokenVerificationResult({
    required this.tokenId,
    required this.isValid,
    this.reason,
  });
}

class TokenVerificationService {
  // Server public key used to verify signatures generated by backend private key.
  // Keep this synchronized with backend key rotation.
  static const String _serverPublicPem = '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsJku7o+1LPVqGPIq+me1
ShFgOy5aULshVUitR5fGpOJ2mdgvwyTKYLBZS6wBCaCNOe4PtGSlU7XAo7rk9dgd
DSioRPOaI41JKlQ5AasVqtnAFDEdfaCnycM9OfJNce0idzHZfIWF5FN9lNftnomD
yKcpgmSShNCDkIGvTZ52n64mX6Fvl2wqbyAEUPS5wzKL2y8v3UQOmmqXmGYbAbZ8
w1aOlPbM98kyE50ishJOqGqkGj48SgL+OeVNrdRmCPp3PFN8sgj+91GFcO+zGHl3
TOW3m5OOITyQDk3HAZnPIyBjxV37mMbvpNlC0udkYSA+g4tkQJSvVchVI+/ytwlM
+wIDAQAB
-----END PUBLIC KEY-----''';

  static RSAPublicKey? _cachedPublicKey;

  static void _log(String message) {
    if (kDebugMode) {
      debugPrint('[TOKEN_VERIFY] $message');
    }
  }

  // Easy-to-call helper when caller only needs a boolean result.
  static Future<bool> isTokenValid(Token token) async {
    _log('isTokenValid called for tokenId=${token.tokenId}');
    final result = await verifyToken(token);
    _log('isTokenValid result tokenId=${token.tokenId} valid=${result.isValid}');
    return result.isValid;
  }

  // Verifies one token using immutable payload + token signature.
  // Signature algorithm matches backend: createSign("SHA256") + sign(privateKey, "base64").
  static Future<TokenVerificationResult> verifyToken(Token token) async {
    try {
      _log('Starting verification for tokenId=${token.tokenId}');

      final immutable = token.immutable;
      if (immutable.isEmpty) {
        _log('Verification failed tokenId=${token.tokenId}: immutable payload missing');
        return TokenVerificationResult(
          tokenId: token.tokenId,
          isValid: false,
          reason: 'Immutable token payload missing',
        );
      }

      final immutableTokenId = (immutable['token_id'] ?? '').toString();
      if (immutableTokenId.isEmpty || immutableTokenId != token.tokenId) {
        _log('Verification failed tokenId=${token.tokenId}: immutable token_id mismatch');
        return TokenVerificationResult(
          tokenId: token.tokenId,
          isValid: false,
          reason: 'Token ID mismatch in immutable payload',
        );
      }

      if (token.signature.trim().isEmpty) {
        _log('Verification failed tokenId=${token.tokenId}: signature missing');
        return TokenVerificationResult(
          tokenId: token.tokenId,
          isValid: false,
          reason: 'Signature missing',
        );
      }

      _log('Preparing RSA verifier for tokenId=${token.tokenId}');
      final publicKey = _cachedPublicKey ?? _parsePublicKey();
      _cachedPublicKey = publicKey;

      // Important: verify exactly the same canonical bytes backend signs:
      // JSON.stringify(data) where data == immutable object.
      final message = jsonEncode(immutable);
      final messageBytes = Uint8List.fromList(utf8.encode(message));
      final signatureBytes = base64Decode(token.signature);

      final verifier = Signer('SHA-256/RSA')
        ..init(false, PublicKeyParameter<RSAPublicKey>(publicKey));
      final isValid = verifier.verifySignature(
        messageBytes,
        RSASignature(signatureBytes),
      );

      if (!isValid) {
        _log('Verification failed tokenId=${token.tokenId}: invalid signature');
        return TokenVerificationResult(
          tokenId: token.tokenId,
          isValid: false,
          reason: 'Invalid signature',
        );
      }

      _log('Verification passed tokenId=${token.tokenId}');

      return TokenVerificationResult(
        tokenId: token.tokenId,
        isValid: true,
      );
    } catch (e) {
      _log('Verification exception tokenId=${token.tokenId}: $e');
      return TokenVerificationResult(
        tokenId: token.tokenId,
        isValid: false,
        reason: 'Verification error: $e',
      );
    }
  }

  // Batch verifier for easy use in recharge, sync, and future transfer flows.
  static Future<List<TokenVerificationResult>> verifyTokens(
    Iterable<Token> tokens,
  ) async {
    _log('verifyTokens called');
    final results = <TokenVerificationResult>[];
    var validCount = 0;
    var invalidCount = 0;

    for (final token in tokens) {
      final result = await verifyToken(token);
      results.add(result);
      if (result.isValid) {
        validCount++;
      } else {
        invalidCount++;
      }
    }

    _log('verifyTokens completed: valid=$validCount invalid=$invalidCount total=${results.length}');
    return results;
  }

  static RSAPublicKey _parsePublicKey() {
    _log('Parsing server public key');
    return CryptoUtils.rsaPublicKeyFromPem(_serverPublicPem);
  }
}
